// Generated by zjema - DO NOT EDIT
const std = @import("std");
const zjema_openapi = @import("zjema_openapi");
pub const backend = zjema_openapi.backend;
const izo = @import("izomorph");

// ============= TYPES =============
pub const Pet = struct {
    id: []const u8,
    name: []const u8,
    tag: ?[]const u8 = null,
};

pub const PetMapper = izo.Mapper(Pet, .{});

pub const NewPet = struct {
    name: []const u8,
    tag: ?[]const u8 = null,
};

pub const NewPetMapper = izo.Mapper(NewPet, .{});



// API Error response
pub const ApiError = struct {
    code: i64,
    message: []const u8,
};
pub const ApiErrorMapper = izo.Mapper(ApiError, .{});

// ============= API CLIENT =============
pub fn ApiClient(comptime Backend: type) type {
    return struct {
        allocator: std.mem.Allocator,
        base_url: []const u8,
        backend: Backend,

        pub fn init(allocator: std.mem.Allocator, base_url: []const u8, _backend: Backend) @This() {
            return .{ .allocator = allocator, .base_url = base_url, .backend = _backend };
        }

        pub fn deinit(self: *@This()) void {
            self.backend.deinit();
        }
    pub fn getPet(self: *@This(), id: []const u8) !Pet {
    const url = try std.fmt.allocPrint(self.allocator, "{s}/pets/{s}", .{ self.base_url, id});
    defer self.allocator.free(url);
    const resp = try self.backend.get(url, &.{});
    defer resp.deinit(self.allocator);
    if (resp.status_code < 200 or resp.status_code >= 300) return error.ApiError;
    return try izo.json.decode(self.allocator, PetMapper, resp.body);
}
    pub fn createPet(self: *@This(), body: NewPet) !Pet {
    const url = try std.fmt.allocPrint(self.allocator, "{s}/pets", .{ self.base_url});
    defer self.allocator.free(url);
    const json_body = try izo.json.encode(self.allocator, body, NewPetMapper, .{});
    defer self.allocator.free(json_body);
    const resp = try self.backend.post(self.allocator, url, json_body, &.{.{ .name = "Content-Type", .value = "application/json" }});
    defer resp.deinit(self.allocator);
    if (resp.status_code < 200 or resp.status_code >= 300) return error.ApiError;
    return try izo.json.decode(self.allocator, PetMapper, resp.body);
}
    };
}
