const std = @import("std");
const zjema = @import("zjema");
const type_gen = @import("codegen/type_generator.zig");
const ast = @import("openapi/ast.zig");

pub const GenerateOptions = struct {
    enable_sse: bool = false,
    int_type: []const u8 = "i64",
    string_type: []const u8 = "[]const u8",
    float_type: []const u8 = "f64",
    bool_type: []const u8 = "bool",
    use_union_for_oneof: bool = true,
    nullable_as_optional: bool = true,
};

pub const ClientGenerator = struct {
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) @This() {
        return .{ .allocator = allocator };
    }

    pub fn generate(self: @This(), spec: anytype, options: GenerateOptions) ![]const u8 {
        var out = std.ArrayList(u8).initCapacity(self.allocator, 4096) catch return error.OutOfMemory;
        errdefer out.deinit(self.allocator);

        const types_code = try type_gen.generateTypes(self.allocator, spec, .{
            .int_type = options.int_type,
            .string_type = options.string_type,
            .float_type = options.float_type,
            .bool_type = options.bool_type,
            .use_union_for_oneof = options.use_union_for_oneof,
            .nullable_as_optional = options.nullable_as_optional,
        });
        defer self.allocator.free(types_code);

        try out.appendSlice(self.allocator,
            \\// Generated by zjema - DO NOT EDIT
            \\const std = @import("std");
            \\const zjema_openapi = @import("zjema_openapi");
            \\pub const backend = zjema_openapi.backend;
            \\const json = zjema_openapi.json;
            \\
            \\// ============= TYPES =============
            \\
        );
        try out.appendSlice(self.allocator, types_code);
        try out.appendSlice(self.allocator, "\n\n");

        try out.appendSlice(self.allocator,
            \\// API Error response
            \\pub const ApiError = struct {
            \\    code: i64,
            \\    message: []const u8,
            \\};
            \\pub const ApiErrorMapper = json.Mapper(ApiError, .{});
            \\
            \\// ============= API CLIENT =============
            \\
        );

        // Pure arena mode - no allocator field
        try out.appendSlice(self.allocator,
            \\pub fn ApiClient(comptime Backend: type) type {
            \\    return struct {
            \\        base_url: []const u8,
            \\        backend: Backend,
            \\
            \\        pub fn init(base_url: []const u8, _backend: Backend) @This() {
            \\            return .{ .base_url = base_url, .backend = _backend };
            \\        }
            \\
            \\        pub fn deinit(self: *@This()) void {
            \\            self.backend.deinit();
            \\        }
            \\
        );

        const type_config = type_gen.TypeGenConfig{};

        var path_it = spec.paths.iterator();
        var path_idx: usize = 0;
        while (path_idx < path_it.len) : (path_idx += 1) {
            const path_str = path_it.keys[path_idx];
            const path_item = path_it.values[path_idx];

            const methods = [_][]const u8{ "get", "put", "post", "delete", "options", "head", "patch", "trace" };
            for (methods) |http_method| {
                const op = if (std.mem.eql(u8, http_method, "get")) path_item.get else if (std.mem.eql(u8, http_method, "put")) path_item.put else if (std.mem.eql(u8, http_method, "post")) path_item.post else if (std.mem.eql(u8, http_method, "delete")) path_item.delete else if (std.mem.eql(u8, http_method, "options")) path_item.options else if (std.mem.eql(u8, http_method, "head")) path_item.head else if (std.mem.eql(u8, http_method, "patch")) path_item.patch else if (std.mem.eql(u8, http_method, "trace")) path_item.trace else null;
                if (op) |operation| {
                    try generateMethod(&out, self.allocator, path_str, http_method, operation, type_config, options);
                }
            }
        }

        try out.appendSlice(self.allocator, "    };\n");
        try out.appendSlice(self.allocator, "}\n");

        return try out.toOwnedSlice(self.allocator);
    }
};

fn isSseResponse(operation: ast.Operation) bool {
    if (operation.responses.get("200")) |resp| {
        if (resp.content.get("text/event-stream")) |_| {
            return true;
        }
    }
    return false;
}

fn generateMethod(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    path: []const u8,
    http_method: []const u8,
    operation: ast.Operation,
    type_config: type_gen.TypeGenConfig,
    options: GenerateOptions,
) !void {
    const method_name = operation.operationId;
    const is_sse = options.enable_sse and isSseResponse(operation);

    // Method signature with arena
    try out.appendSlice(allocator, "    pub fn ");
    try out.appendSlice(allocator, method_name);
    try out.appendSlice(allocator, "(self: *@This(), arena: std.mem.Allocator");

    var has_json_body = false;
    var body_type_owned: []const u8 = "";
    var return_type_owned: []const u8 = undefined;
    if (operation.requestBody) |rb| {
        if (rb.content.get("application/json")) |json_media| {
            has_json_body = true;
            body_type_owned = try getParamTypeString(allocator, json_media.schema, type_config);
            errdefer allocator.free(body_type_owned);
        }
    }

    for (operation.parameters) |param| {
        const param_type = try getParamTypeString(allocator, param.schema, type_config);
        defer allocator.free(param_type);
        try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, param.name);
        try out.appendSlice(allocator, ": ");
        try out.appendSlice(allocator, param_type);
    }

    if (has_json_body) {
        try out.appendSlice(allocator, ", body: ");
        try out.appendSlice(allocator, body_type_owned);
    }

    const fmt_path = try transformPath(allocator, path);
    defer allocator.free(fmt_path);
    const full_fmt = try std.fmt.allocPrint(allocator, "{s}{s}", .{ "{s}", fmt_path });
    defer allocator.free(full_fmt);

    if (is_sse) {
        try out.appendSlice(allocator, ") anytype! {\n");
        try out.appendSlice(allocator, "    const url = try std.fmt.allocPrint(arena, \"");
        try escapeString(allocator, out, full_fmt);
        try out.appendSlice(allocator, "\", .{self.base_url");
        var i: usize = 0;
        while (i < path.len) {
            if (path[i] == '{') {
                const end = std.mem.indexOfScalarPos(u8, path, i, '}') orelse break;
                try out.appendSlice(allocator, ", ");
                try out.appendSlice(allocator, path[i + 1 .. end]);
                i = end + 1;
            } else {
                i += 1;
            }
        }
        try out.appendSlice(allocator, "});\n");
        try out.appendSlice(allocator, "    return try self.backend.getStream(url, &.{});\n");
        try out.appendSlice(allocator, "}\n");
        return;
    } else if (operation.responses.get("200")) |resp| {
        if (resp.content.get("application/json")) |json_media| {
            return_type_owned = try getParamTypeString(allocator, json_media.schema, type_config);
            try out.appendSlice(allocator, ") !");
            try out.appendSlice(allocator, return_type_owned);
            try out.appendSlice(allocator, " {\n");
        } else {
            try out.appendSlice(allocator, ") void {\n");
        }
    } else {
        try out.appendSlice(allocator, ") void {\n");
    }

    // Build URL using arena - no errdefer needed
    try out.appendSlice(allocator, "    const url = try std.fmt.allocPrint(arena, \"");
    try escapeString(allocator, out, full_fmt);
    try out.appendSlice(allocator, "\", .{ self.base_url");
    var i: usize = 0;
    while (i < path.len) {
        if (path[i] == '{') {
            const end = std.mem.indexOfScalarPos(u8, path, i, '}') orelse break;
            try out.appendSlice(allocator, ", ");
            try out.appendSlice(allocator, path[i + 1 .. end]);
            i = end + 1;
        } else {
            i += 1;
        }
    }
    try out.appendSlice(allocator, "});\n");

    // Encode body using arena
    if (has_json_body) {
        try out.appendSlice(allocator, "    const json_body = try json.encode(arena, body, ");
        try out.appendSlice(allocator, body_type_owned);
        try out.appendSlice(allocator, "Mapper, .{});\n");
    }

    // Backend call
    try out.appendSlice(allocator, "    const resp = try self.backend.");
    try out.appendSlice(allocator, http_method);
    if (has_json_body) {
        try out.appendSlice(allocator, "(url, json_body, &.{.{ .name = \"Content-Type\", .value = \"application/json\" }});\n");
    } else {
        try out.appendSlice(allocator, "(url, &.{});\n");
    }

    // Copy to arena and free backend response - no errdefer
    try out.appendSlice(allocator, "    const body_copy = try arena.dupe(u8, resp.body);\n");
    try out.appendSlice(allocator, "    resp.deinit();\n");

    try out.appendSlice(allocator, "    if (resp.status_code < 200 or resp.status_code >= 300) return error.ApiError;\n");

    // Decode using arena
    if (operation.responses.get("200")) |resp| {
        if (resp.content.get("application/json") != null) {
            if (return_type_owned.len > 0) {
                try out.appendSlice(allocator, "    return try json.decode(arena, ");
                try out.appendSlice(allocator, return_type_owned);
                try out.appendSlice(allocator, "Mapper, body_copy, .{});\n");
            }
        }
    }

    try out.appendSlice(allocator, "}\n");

    if (has_json_body) {
        allocator.free(body_type_owned);
    }
    if (return_type_owned.len > 0) {
        allocator.free(return_type_owned);
    }
}

fn getParamTypeString(
    allocator: std.mem.Allocator,
    schema: ast.Schema,
    config: type_gen.TypeGenConfig,
) ![]const u8 {
    if (schema == .ref) {
        const ref = schema.ref;
        const last_slash = std.mem.lastIndexOf(u8, ref, "/");
        const name = if (last_slash) |idx| ref[idx + 1 ..] else ref;
        return try allocator.dupe(u8, name);
    } else if (schema == .object) {
        const obj = schema.object;
        const t = obj.type orelse {
            return try allocator.dupe(u8, config.string_type);
        };
        if (std.mem.eql(u8, t, "string")) {
            return try allocator.dupe(u8, config.string_type);
        } else if (std.mem.eql(u8, t, "integer")) {
            return try allocator.dupe(u8, config.int_type);
        } else if (std.mem.eql(u8, t, "number")) {
            return try allocator.dupe(u8, config.float_type);
        } else if (std.mem.eql(u8, t, "boolean")) {
            return try allocator.dupe(u8, config.bool_type);
        } else if (std.mem.eql(u8, t, "array")) {
            const items_schema = obj.items orelse {
                return try allocator.dupe(u8, "[]const u8");
            };
            const item_type = try getParamTypeString(allocator, items_schema, config);
            defer allocator.free(item_type);
            return try std.fmt.allocPrint(allocator, "[]const {s}", .{item_type});
        } else {
            return try allocator.dupe(u8, "[]const u8");
        }
    }
    return error.InvalidSchema;
}

fn escapeString(allocator: std.mem.Allocator, out: *std.ArrayList(u8), s: []const u8) !void {
    var i: usize = 0;
    while (i < s.len) : (i += 1) {
        switch (s[i]) {
            '\\', '"' => {
                try out.appendSlice(allocator, "\\");
                try out.appendSlice(allocator, s[i .. i + 1]);
            },
            '\n' => {
                try out.appendSlice(allocator, "\\n");
            },
            else => {
                try out.appendSlice(allocator, s[i .. i + 1]);
            },
        }
    }
}

fn transformPath(allocator: std.mem.Allocator, path: []const u8) ![]const u8 {
    var out = std.ArrayList(u8).initCapacity(allocator, 0) catch unreachable;
    defer out.deinit(allocator);
    var i: usize = 0;
    while (i < path.len) {
        if (path[i] == '{') {
            const end = std.mem.indexOfScalarPos(u8, path, i, '}') orelse {
                try out.appendSlice(allocator, path[i..]);
                break;
            };
            try out.appendSlice(allocator, "{s}");
            i = end + 1;
        } else {
            try out.appendSlice(allocator, path[i .. i + 1]);
            i += 1;
        }
    }
    return try out.toOwnedSlice(allocator);
}
