const std = @import("std");
const type_gen = @import("codegen/type_generator.zig");
const ast = @import("openapi/ast.zig");

pub const ClientGenerator = struct {
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) @This() {
        return .{ .allocator = allocator };
    }

    pub fn generate(self: @This(), spec: anytype) ![]const u8 {
        var out = std.ArrayList(u8).initCapacity(self.allocator, 4096) catch return error.OutOfMemory;
        errdefer out.deinit(self.allocator);

        // Generate types using type_generator (includes structs + mappers)
        const types_code = try type_gen.generateTypes(self.allocator, spec, .{});
        defer self.allocator.free(types_code);

        try out.appendSlice(self.allocator,
            \\// Generated by zjema - DO NOT EDIT
            \\const std = @import("std");
            \\const izo = @import("izomorph");
            \\
            \\// ============= TYPES =============
            \\
        );
        try out.appendSlice(self.allocator, types_code);
        try out.appendSlice(self.allocator, "\n\n");

        // API Error response (generic)
        try out.appendSlice(self.allocator,
            \\// API Error response
            \\pub const ApiError = struct {
            \\    code: i64,
            \\    message: []const u8,
            \\};
            \\pub const ApiErrorMapper = izo.Mapper(ApiError, .{});
            \\
            \\// ============= API CLIENT =============
            \\
        );

        // ApiClient generic skeleton
        try out.appendSlice(self.allocator,
            \\pub const ApiClient(comptime Backend: type) = struct {
            \\    allocator: std.mem.Allocator,
            \\    base_url: []const u8,
            \\    backend: Backend,
            \\
            \\    pub fn init(allocator: std.mem.Allocator, base_url: []const u8, backend: Backend) @This() {
            \\        return .{ .allocator = allocator, .base_url = base_url, .backend = backend };
            \\    }
            \\
            \\    pub fn deinit(self: *@This()) void {
            \\        self.backend.deinit();
            \\    }
            \\
        );

        const config = type_gen.TypeGenConfig{};

        // Generate methods from all paths
        var path_it = spec.paths.iterator();
        var path_idx: usize = 0;
        while (path_idx < path_it.len) : (path_idx += 1) {
            const path_str = path_it.keys[path_idx];
            const path_item = path_it.values[path_idx];

            // Supported HTTP methods
            const methods = [_][]const u8{ "get", "put", "post", "delete", "options", "head", "patch", "trace" };
            for (methods) |http_method| {
                const op = if (std.mem.eql(u8, http_method, "get")) path_item.get
                else if (std.mem.eql(u8, http_method, "put")) path_item.put
                else if (std.mem.eql(u8, http_method, "post")) path_item.post
                else if (std.mem.eql(u8, http_method, "delete")) path_item.delete
                else if (std.mem.eql(u8, http_method, "options")) path_item.options
                else if (std.mem.eql(u8, http_method, "head")) path_item.head
                else if (std.mem.eql(u8, http_method, "patch")) path_item.patch
                else if (std.mem.eql(u8, http_method, "trace")) path_item.trace
                else null;
                if (op) |operation| {
                    try generateMethod(&out, self.allocator, path_str, http_method, operation, config);
                }
            }
        }

        // Close ApiClient struct
        try out.appendSlice(self.allocator, "};\n");

        return try out.toOwnedSlice(self.allocator);
    }
};

// Replace {param} with {}
fn transformPath(allocator: std.mem.Allocator, path: []const u8) ![]const u8 {
    var out = std.ArrayList(u8){};
    var i: usize = 0;
    while (i < path.len) {
        if (path[i] == '{') {
            const end = std.mem.indexOfScalarPos(u8, path, i, '}') orelse {
                try out.appendSlice(allocator, path[i..]);
                break;
            };
            try out.appendSlice(allocator, "{}");
            i = end + 1;
        } else {
            try out.appendSlice(allocator, path[i..i+1]);
            i += 1;
        }
    }
    return out.toOwnedSlice(allocator);
}

// Escape a string for inclusion in a Zig string literal
fn escapeString(allocator: std.mem.Allocator, out: *std.ArrayList(u8), s: []const u8) !void {
    var i: usize = 0;
    while (i < s.len) : (i += 1) {
        switch (s[i]) {
            '\\', '\"' => {
                try out.appendSlice(allocator, "\\");
                try out.appendSlice(allocator, s[i..i+1]);
            },
            '\n' => {
                try out.appendSlice(allocator, "\\n");
            },
            else => {
                try out.appendSlice(allocator, s[i..i+1]);
            },
        }
    }
}

// Determine the Zig type string for a schema (mirrors type_generator logic)
fn getParamTypeString(
    allocator: std.mem.Allocator,
    schema: ast.Schema,
    config: type_gen.TypeGenConfig,
) ![]const u8 {
    if (schema == .ref) {
        const ref = schema.ref;
        const last_slash = std.mem.lastIndexOf(u8, ref, "/");
        const name = if (last_slash) |idx| ref[idx+1..] else ref;
        return try allocator.dupe(u8, name);
    } else if (schema == .object) {
        const obj = schema.object;
        const t = obj.type orelse {
            return try allocator.dupe(u8, config.string_type);
        };
        if (std.mem.eql(u8, t, "string")) {
            return try allocator.dupe(u8, config.string_type);
        } else if (std.mem.eql(u8, t, "integer")) {
            return try allocator.dupe(u8, config.int_type);
        } else if (std.mem.eql(u8, t, "number")) {
            return try allocator.dupe(u8, config.float_type);
        } else if (std.mem.eql(u8, t, "boolean")) {
            return try allocator.dupe(u8, "bool");
        } else if (std.mem.eql(u8, t, "array")) {
            const items_schema = obj.items orelse {
                return try allocator.dupe(u8, "[]const u8");
            };
            const item_type = try getParamTypeString(allocator, items_schema, config);
            defer allocator.free(item_type);
            return try std.fmt.allocPrint(allocator, "[]const {s}", .{item_type});
        } else {
            // Inline object or unknown, treat as opaque
            return try allocator.dupe(u8, "[]const u8");
        }
    }
    return error.InvalidSchema;
}

// generateMethod writes a single API method
fn generateMethod(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    path: []const u8,
    http_method: []const u8,
    operation: ast.Operation,
    config: type_gen.TypeGenConfig,
) !void {
    const method_name = operation.operationId;

    // Start method signature
    try out.appendSlice(allocator, "    pub fn ");
    try out.appendSlice(allocator, method_name);
    try out.appendSlice(allocator, "(self: *@This()");

    // Request body handling (JSON only)
    var has_json_body = false;
    var body_type_owned: []const u8 = "";
    if (operation.requestBody) |rb| {
        if (rb.content.get("application/json")) |json_media| {
            has_json_body = true;
            body_type_owned = try getParamTypeString(allocator, json_media.schema, config);
            errdefer allocator.free(body_type_owned);
        }
    }

    // Add parameters from operation (all become method args)
    for (operation.parameters) |param| {
        const param_type = try getParamTypeString(allocator, param.schema, config);
        defer allocator.free(param_type);
        try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, param.name);
        try out.appendSlice(allocator, ": ");
        try out.appendSlice(allocator, param_type);
    }

    // Add body parameter if present
    if (has_json_body) {
        try out.appendSlice(allocator, ", body: ");
        try out.appendSlice(allocator, body_type_owned);
    }

    // Determine return type
    var returns_void = true;
    var return_type_owned: []const u8 = "";
    if (operation.responses.get("200")) |resp| {
        if (resp.content.get("application/json")) |json_media| {
            return_type_owned = try getParamTypeString(allocator, json_media.schema, config);
            try out.appendSlice(allocator, ") !");
            try out.appendSlice(allocator, return_type_owned);
            returns_void = false;
        } else {
            try out.appendSlice(allocator, ") void {\n");
        }
    } else {
        try out.appendSlice(allocator, ") void {\n");
    }
    if (!returns_void) {
        try out.appendSlice(allocator, " {\n");
    }

    // Build URL: transformPath replaces {param} with {}
    const fmt_path = try transformPath(allocator, path);
    defer allocator.free(fmt_path);

    try out.appendSlice(allocator, "    const url = try std.fmt.allocPrint(self.allocator, \"");
    try escapeString(allocator, out, fmt_path);
    try out.appendSlice(allocator, "\", .{ self.base_url");

    // Append path parameters in order of appearance
    var i: usize = 0;
    while (i < path.len) {
        if (path[i] == '{') {
            const end = std.mem.indexOfScalarPos(u8, path, i, '}') orelse break;
            try out.appendSlice(allocator, ", ");
            try out.appendSlice(allocator, path[i+1..end]);
            i = end + 1;
        } else {
            i += 1;
        }
    }
    try out.appendSlice(allocator, "});\n");
    try out.appendSlice(allocator, "    defer self.allocator.free(url);\n");

    // Encode request body if present
    if (has_json_body) {
        try out.appendSlice(allocator, "    const json_body = try izo.json.encode(self.allocator, body, ");
        try out.appendSlice(allocator, body_type_owned);
        try out.appendSlice(allocator, "Mapper, .{});\n");
        try out.appendSlice(allocator, "    defer self.allocator.free(json_body);\n");
    }

    // Backend call
    const is_simple = std.mem.eql(u8, http_method, "get") or std.mem.eql(u8, http_method, "delete") or
        std.mem.eql(u8, http_method, "head") or std.mem.eql(u8, http_method, "options") or
        std.mem.eql(u8, http_method, "trace");
    try out.appendSlice(allocator, "    const resp = try self.backend.");
    try out.appendSlice(allocator, http_method);
    if (has_json_body) {
        try out.appendSlice(allocator, "(self.allocator, url, json_body, &.{.{ .name = \"Content-Type\", .value = \"application/json\" }});\n");
    } else if (is_simple) {
        try out.appendSlice(allocator, "(url, &.{});\n");
    } else {
        // PUT/PATCH without body? Still use simple call
        try out.appendSlice(allocator, "(url, &.{});\n");
    }
    try out.appendSlice(allocator, "    defer resp.deinit(self.allocator);\n");

    // Status check (2xx)
    try out.appendSlice(allocator, "    if (resp.status_code < 200 or resp.status_code >= 300) return error.ApiError;\n");

    // Response decoding if not void
    if (!returns_void) {
        try out.appendSlice(allocator, "    return try izo.json.decode(self.allocator, ");
        try out.appendSlice(allocator, return_type_owned);
        try out.appendSlice(allocator, "Mapper, resp.body);\n");
    }

    try out.appendSlice(allocator, "}\n");

    // Cleanup allocated type strings
    if (has_json_body) {
        allocator.free(body_type_owned);
    }
    if (return_type_owned.len > 0) {
        allocator.free(return_type_owned);
    }
}
