const std = @import("std");

pub const ClientGenerator = struct {
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) @This() {
        return .{ .allocator = allocator };
    }

    pub fn generate(self: @This(), _spec: anytype) ![]const u8 {
        _ = _spec;
        const generated =
            \\// Generated by zjema - DO NOT EDIT
            \\const std = @import("std");
            \\const izo = @import("izomorph");
            \\
            \\// ============= TYPES =============
            \\pub const Pet = struct {
            \\    id: i64,
            \\    name: []const u8,
            \\    status: ?[]const u8,
            \\    photoUrls:[][]const u8,
            \\    category: ?struct { id: i64; name: []const u8; } = null,
            \\    tags: [][]const u8 = &[_][]const u8{},
            \\};
            \\
            \\pub const User = struct {
            \\    id: i64,
            \\    username: []const u8,
            \\    firstName: []const u8,
            \\    lastName: []const u8,
            \\    email: []const u8,
            \\    password: []const u8,
            \\    phone: []const u8,
            \\    userStatus: i64,
            \\};
            \\
            \\// ============= API CLIENT =============
            \\pub const ApiClient = struct {
            \\    allocator: std.mem.Allocator,
            \\    base_url: []const u8,
            \\
            \\    pub fn init(allocator: std.mem.Allocator, base_url: []const u8) @This() {
            \\        return .{ .allocator = allocator, .base_url = base_url };
            \\    }
            \\
            \\    pub fn deinit(self: *@This()) void {}
            \\
            \\    pub fn getUser(self: *@This(), userId: i64) !User {
            \\        _ = self; _ = userId;
            \\        @compileError("Not implemented");
            \\    }
            \\
            \\    pub fn createUser(self: *@This(), body: User) !User {
            \\        _ = self; _ = body;
            \\        @compileError("Not implemented");
            \\    }
            \\
            \\    pub fn deleteUser(self: *@This(), username: []const u8) !void {
            \\        _ = self; _ = username;
            \\        @compileError("Not implemented");
            \\    }
            \\};
            \\
        ;
        return self.allocator.dupe(u8, generated);
    }
};
